version: '3.8'

services:
  server:
    # image: 'nginx:stable-alpine'
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html 
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro # https://hub.docker.com/_/nginx
    depends_on:
      - php
      - mysql
  php:
    # image: 'php:8.0-fpm-alpine'
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  mysql:
    image: mysql:5.7
    platform: linux/amd64 # Mac M1 issue 
    # FYI, https://velog.io/@sujeongim/%EC%98%A4%EB%A5%98-%EC%B2%9C%EA%B5%AD-Docker%ED%8E%B8-Mac-M1-no-matching-manifest-for-linuxarm64v8
    env_file:
      - ./env/mysql.env
  composer:
    # image: 'composer:latest'
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ['php', '/var/www/html/artisan'] # php 명령어로 artisan 파일 실행. dockerfile 내부의 설정을 오버라이딩
  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ['npm']
    volumes:
      - ./src:/var/www/html
